rango/urls.py
from django.urls import path
from rango import views

app_name = 'rango'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('add_category/', views.add_category, name='add_category'),
    path('category/<slug:category_name_slug>/', 
         views.show_category, name='show_category'),
    path('category/<slug:category_name_slug>/add_page/', 
         views.add_page, name='add_page'),
    path('track_url/', views.track_url, name='track_url'),
]

tango_with_django_project/urls.py
from django.contrib import admin
from django.urls import path, include
from rango import views

urlpatterns = [
    path('', views.index, name='index'),
    path('rango/', include('rango.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),  # ADD THIS LINE
]

rango/models.py
from django.db import models
from django.urls import reverse
from django.template.defaultfilters import slugify

class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)
    
    def save(self, *args, **kwargs):
        self.slug = self.name.replace(' ', '-')
        super(Category, self).save(*args, **kwargs)
    
    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name_plural = 'Categories'
    
    def get_absolute_url(self):
        return reverse('rango:show_category', kwargs={'category_name_slug': self.slug})
    
    # BOOK CHAPTER 10 EXACT:
    def likes_button(self):
        return f'<button type="button" class="btn btn-primary" name="category_id" value="{self.id}">Like Category</button>'
    
    likes_button.allow_tags = True
    likes_button.short_description = 'Like'

class Page(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.IntegerField(default=0)
    
    def __str__(self):
        return self.title

rango/forms.py
from django import forms
from rango.models import Category, Page


class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128,
                           help_text="Please enter the category name.")

    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = Category
        fields = ('name',)


class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128,
                            help_text="Please enter the title of the page.")
    url = forms.URLField(max_length=200,
                         help_text="Please enter the URL of the page.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    class Meta:
        model = Page
        exclude = ('category',)

    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')

        if url and not url.startswith('http://') and not url.startswith('https://'):
            url = f'http://{url}'
            cleaned_data['url'] = url

        return cleaned_data

rango/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from rango.models import Category, Page
from rango.forms import CategoryForm, PageForm

def index(request):
    category_list = Category.objects.order_by('-likes')[:5]
    page_list = Page.objects.order_by('-views')[:5]
    context_dict = {
        'boldmessage': 'Crunchy, creamy, cookie, candy, cupcake!',
        'categories': category_list,
        'pages': page_list,
    }
    return render(request, 'rango/index.html', context_dict)

def about(request):
    return render(request, 'rango/about.html')

def show_category(request, category_name_slug):
    context_dict = {}
    
    try:
        category = Category.objects.get(slug=category_name_slug)
        pages = Page.objects.filter(category=category).order_by('-views')
        context_dict['pages'] = pages
        context_dict['category'] = category
    except Category.DoesNotExist:
        context_dict['pages'] = None
        context_dict['category'] = None
    
    return render(request, 'rango/category.html', context_dict)

def add_category(request):
    form = CategoryForm()
    
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return redirect('rango:index')
        else:
            print(form.errors)
    
    return render(request, 'rango/add_category.html', {'form': form})

def add_page(request, category_name_slug):
    try:
        category = Category.objects.get(slug=category_name_slug)
    except Category.DoesNotExist:
        category = None
    
    if category is None:
        return redirect('rango:index')
    
    form = PageForm()
    
    if request.method == 'POST':
        form = PageForm(request.POST)
        if form.is_valid():
            if form.cleaned_data['url'] and form.cleaned_data['url'].startswith('http'):
                page = form.save(commit=False)
                page.category = category
                page.views = 0
                page.save()
                return redirect('rango:show_category', category_name_slug=category_name_slug)
        else:
            print(form.errors)
    
    context_dict = {'form': form, 'category': category}
    return render(request, 'rango/add_page.html', context_dict)

def track_url(request):
    next_url = None
    if request.method == 'GET':
        if 'category_id' in request.GET:
            category_id = request.GET['category_id']
            try:
                category = Category.objects.get(id=category_id)
                category.likes += 1  # ← FIXED: likes not views!
                category.save()
                next_url = category.get_absolute_url()
            except:
                next_url = '/rango/'
        else:
            next_url = '/rango/'
    
    response = redirect(next_url)
    return response

templates/rango/about.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
    <title>Rango</title>
</head>
<body>
    <h1>Rango says...</h1>
    <div>
        here is the about page.<br />
    </div>
    <div>
        <a href="/rango/">Index</a><br />
        <img src="{% static 'images/rango.jpg' %}" alt="Picture of Rango" />
    </div>
</body>
</html>

templates/rango/add_category.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <title>Rango - Add a Category</title>
</head>
<body>
    <h1>Add a Category</h1>
    <form id="category_form" method="post" action="{% url 'rango:add_category' %}">
        {% csrf_token %}
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Add Category" />
    </form>
    <br/>
    <a href="{% url 'rango:index' %}">Index</a><br/>
    <img src="{% static 'images/rango.jpg' %}" alt="Rango">
</body>
</html>

templates/rango/add_page.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
    <title>Rango</title>
</head>
<body>
    <h1>Add a Page to {{ category.name }}</h1>
    <div>
        <form id="page_form"
              method="post"
              action="{% url 'rango:add_page' category.slug %}">
            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}
            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}<br />
                {{ field }}<br />
            {% endfor %}
            <input type="submit" name="submit" value="Add Page" />
        </form>
    </div>
    <div>
        <a href="{% url 'rango:show_category' category.slug %}">Back to category</a>
    </div>
</body>
</html>

templates/rango/category.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <title>Rango - {{ category.name }}</title>
</head>
<body>
    <h1>{{ category.name }}</h1>
    
    {% if category %}
        <h2>Pages in {{ category.name }}</h2>
        {% if pages %}
            <ul>
            {% for page in pages %}
                <li><a href="{{ page.url }}">{{ page.title }}</a></li>
            {% endfor %}
            </ul>
        {% else %}
            <strong>No pages currently in category.</strong>
        {% endif %}
    {% endif %}
    
    <a href="{% url 'rango:index' %}">Index</a><br/>
    <img src="{% static 'images/rango.jpg' %}" alt="Rango">
</body>
</html>

templates/rango/index.html
<h2>Most Liked Categories</h2>
{% if categories %}
<ul class="list-group">
{% for category in categories %}
    <li class="list-group-item">
        <a href="{{ category.get_absolute_url }}">{{ category.name }}</a> 
        ({{ category.likes }}) 
        {{ category.likes_button|safe }}
    </li>
{% endfor %}
</ul>
{% else %}
    <strong>There are no categories present.</strong>
{% endif %}